@startuml


/'    note top of ASSOCIATION #white
    note about
    ASSOCIATION
    end note'/

package ASSOCIATION <<Rectangle>>{

    class Chain {
            +{field} Anchor front
            +{field} Anchor back
        --
            +{method} anchorUp (Anchor)
    }

    class Anchor {
            +{field} Chain chain
        --
'            +{method} enchain (Chain)
    }


    Chain "1" -- "*" Anchor : +anchorUp >

    hide members
}

@enduml